version: '3.7'
services:
  db:    
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_DB: "inventory"
      POSTGRES_PASSWORD: "Postgresdb"
    ports:
      - "5432:5432"

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@icehead.com"
      PGADMIN_DEFAULT_PASSWORD: "admin!123"
    ports:
      - "16543:80"
    depends_on:
      - db      